easy_admin:
    design:
        #form_theme: ['@FOSCKEditor/Form/ckeditor_widget.html.twig']
        form_theme:
          - '@EasyAdmin/form/bootstrap_4.html.twig'
          - '@FOSCKEditor/Form/ckeditor_widget.html.twig'

    entities:
        Booking:
              class: App\Entity\Booking
              form:
                    fields:
                          - { property: 'client' }
                          - { property: 'passenger' }

                          - { property: 'travelDate' }
                          - { property: 'travelTime' }
                          - { property: 'price'}
                          - { property: 'currency', type: 'choice', type_options: '%easyadmin.options.currency.choices%' }

                          - { property: 'origin' }
                          - { property: 'destination' }
                          - { property: 'comment' }
              list:
                    fields:
                        - { property: 'id' }
                        - { property: 'client' }
                        - { property: 'passenger' }
                        - { property: 'travelDate' }
                        - { property: 'travelTime'}
                        - { property: 'destination'}
                        - { property: 'destination'}
                        - { property: 'price'}
                        - { property: 'currency'}

        Client:
             class: App\Entity\Client
             form:
                   fields:
                         - { property: 'name' }
                         - { property: 'email' }
                         - { property: 'telephone' }
                         - { property: 'country'}
                         - { property: 'locale', type: 'choice', type_options: '%easyadmin.options.language.choices%' }
                         - { property: 'bookings' }
        Place:
              class: App\Entity\Place
              form:
                  fields:
                      - { property: 'location' }
        TaxiService:
              class: App\Entity\TaxiService
              show:
                   fields:
                      - { property: 'id' }
                      - { property: 'active' }
                      - { property: 'internalName' }
                      - { property: 'category' }
                      - { property: 'image', type: 'image', base_path: '%app.path.uploaded_images%' }
                      - { property: 'AlternativeText' }
                      - { property: 'updatedAt' }
                      - { property: 'origin' }
                      - { property: 'intermedialPlaces' }
                      - { property: 'destination' }
                      - { property: 'translations' }

              list:
                    fields:
                        - { property: 'internalName' }
                        - { property: 'active' }
                        - { property: 'image', type: 'image', base_path: '%app.path.uploaded_images%' }
                        - { property: 'category'}
                        - { property: 'origin'}
                        - { property: 'destination'}
              form:
                  fields:
                    - { property: 'internalName' }
                    - { property: 'active' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - { property: 'alternativeText'}
                    - { property: 'category', type: 'choice', type_options: '%easyadmin.options.service_categories.choices%' }
                    - { property: 'origin'}
                    - { property: 'intermedialPlaces'}
                    - { property: 'destination'}
                    - { property: 'translations'}
        TaxiServiceTranslation:
              class: App\Entity\TaxiServiceTranslation
              form:
                  fields:
                        - { property: 'translatable', label: 'Translation from', }
                        - { property: 'locale', type: 'choice', type_options: '%easyadmin.options.language.choices%' }
                        - { property: 'name' }
                        - { property: 'description', type: 'fos_ckeditor'}


