easy_admin:
    design:
        form_theme:
          - '@EasyAdmin/form/bootstrap_4.html.twig'
          - '@FOSCKEditor/Form/ckeditor_widget.html.twig'
          - '@HabanaTech_BusinessModel\metadata_translation_bootstrap_4_layout.html.twig'

    entities:
        Client:
             class: App\Entity\Client
             form:
                   fields:
                         - { property: 'name' }
                         - { property: 'email' }
                         - { property: 'telephone' }
                         - { property: 'country'}
                         - { property: 'locale', type: 'choice', type_options: '%easyadmin.options.language.choices%' }
                         - { property: 'bookings' }

        Booking:
              class: App\Entity\Booking
              form:
                    fields:
                          - { property: 'client', label: 'Cliente', help: 'Selecciona un cliente existente, o agrega uno nuevo.', type_options: {attr: {required: false}} }
                          - { property: 'newClient', label: 'Nuevo Cliente', help: 'Puede agregar un nuevo cliente aqui' , type: 'App\Form\ClientType'}
                          - { property: 'passenger', type_options: {attr: { min: 1} }, label: 'Cantidad de pasajeros' }

                          - { property: 'travelDate', label: 'Fecha del viaje' }
                          - { property: 'travelTime', label: 'Hora del viaje' }
                          - { property: 'price',  label: 'Precio', type: 'money' }
                          - { property: 'currency', label: 'Moneda a cobrar', type: 'choice', type_options: '%easyadmin.options.currency.choices%' }

                          - { property: 'origin', label: 'Lugar de destino' }
                          - { property: 'destination', label: 'Lugar de destino' }
                          - { property: 'comment', label: 'Comentario del cliente' }
              list:
                    fields:
                        - { property: 'id' }
                        - { property: 'client' }
                        - { property: 'passenger' }
                        - { property: 'travelDate' }
                        - { property: 'travelTime'}
                        - { property: 'destination'}
                        - { property: 'destination'}
                        - { property: 'price'}
                        - { property: 'currency'}

        Place:
              class: App\Entity\Place
              form:
                  fields:
                      - { property: 'name' }
                      - { property: 'public' }
                      - { property: 'address' }
                      - { property: 'lngLat', label: 'Longitud y Latitud', help: 'Seleccione un punto en el mapa para rellenar automaticamente' , type: 'text'}
                      - { property: 'referencePlace', label: 'Punto de referencia', help: 'Cuando se llena automaticamente, se refiere a un punto relativamente cercano al marcado realmente',  type: 'text'}
              templates:
                  edit: 'dash/board/customizations/place/edit.html.twig'
                  new: 'dash/board/customizations/place/new.html.twig'

        Services:
              class: App\Entity\Service
              show:
                   fields:
                      - { property: 'id' }
                      - { property: 'active' }
#                      - { property: 'name' }
#                      - { property: 'category' }
                      - { property: 'image', type: 'image', base_path: '%app.path.uploaded_images%' }
                      - { property: 'AlternativeText' }
                      - { property: 'updatedAt' }
                      - { property: 'origin' }
                      - { property: 'intermediatePlaces' }
                      - { property: 'destination' }
                      - { property: 'translations' }

              list:
                    fields:
                        - { property: 'active' }
                        - { property: 'name' }
                        - { property: 'image', type: 'image', base_path: '%app.path.uploaded_images%' }
                        - { property: 'category'}
                        - { property: 'origin'}
                        - { property: 'destination'}
              form:
                  fields:
                    - { type: 'tab' , label: 'Información general del Recorrido' }
                    - { type: 'group', label: 'Lugares', icon: 'gear', columns: 8 }
                    - { type: 'section', label: 'User Details' }
                    - { property: 'title', label: 'Titulo', type: 'HabanaTech\BusinessModel\Form\MetadataTranslationType', type_options: { field: 'title'} }
                    - { property: 'description', type: 'HabanaTech\BusinessModel\Form\MetadataTranslationType', type_options: { field: 'description',  'current_field_type': FOS\CKEditorBundle\Form\Type\CKEditorType } }
#                    - { property: 'translations', type: A2lix\TranslationFormBundle\Form\Type\TranslationsType, type_options: { fields: {'description': { 'field_type': FOS\CKEditorBundle\Form\Type\CKEditorType } }  } }


                    - { type: 'group', label: 'Administrar', icon: 'gear', columns: 4 }
#                    - { property: 'translations.name', type: A2lix\TranslationFormBundle\Form\Type\TranslatedEntityType }
                    - { type: 'section', label: 'Origen' }
                    - { property: 'name', label: 'Nombre interno' }
                    - { property: 'active', label: 'Activar servicio' }
                    - { property: 'priority', label: 'Prioridad', help: 'Los mayores valor se muestran primero al cliente' }

                    - { type: 'group', label: 'Lugares', icon: 'gear', columns: 8 }
                    - { type: 'section', label: 'Origen' }
                    - { property: 'origin'}

                    - { type: 'section', label: 'Puntos intermedios' }
                    - { property: 'intermediatePlaces'}

                    - { type: 'section', label: 'Destino final' }
                    - { property: 'destination'}



                    - { type: 'tab' , label: 'Información Básica',  icon: 'phone'  }
                    - { property: 'internalName', type: 'fos_ckeditor' }
                    - { type: 'tab' , label: 'Información mas Básica',  icon: 'phone'  }
                    - { property: 'active' }

                    - { property: 'imageField', label: 'Main Image', help: 'You can replace the current image with one from gallery or upload a new one', type: 'HabanaTech\BusinessModel\Form\SingleImageFromGalleryType',  type_options: { block_name: 'image_field' }}
                    - { property: 'alternativeText'}
#                    - { property: 'category', type: 'choice', type_options: '%easyadmin.options.service_categories.choices%' }



#                    - { property: 'name' }
#                    - { property: 'description', type: 'fos_ckeditor'}

#        GalleryImage:
#              class: App\Entity\GalleryImage
#              form:
#                  fields:
###                      - { property: 'title'}
#                      - { property: 'imageFile', type: 'vich_image' }
###                      - { property: 'alternativeText'}
###                      - { property: 'taxiService'}
##              list:
##                  fields:
##                      - { property: 'title'}
##                      - { property: 'image', type: 'image', base_path: '%app.path.uploaded_images%' }
##                      - { property: 'taxiService'}
##
#
