easy_admin:
    entities:
        Booking:
            class: App\Entity\Booking
        Client:
            class: App\Entity\Client
        Place:
            class: App\Entity\Place
        TaxiService:
              class: App\Entity\TaxiService
              form:
                  fields:
                  #  - { property: 'imageFile', type: 'vich_image' }
