vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: '%kernel.project_dir%/uploads/images'
            upload_destination: '%kernel.project_dir%/public/uploads/images'
            #namer: Vich\UploaderBundle\Naming\OrignameNamer
            namer: Vich\UploaderBundle\Naming\HashNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
